name = "NetcdfIO"
uuid = "6a36f34d-89cf-423a-87c4-84549e82f670"
version = "0.2.12"
authors = ["Yujie Wang <jesiner@gmail.com>"]

[deps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
NetCDF_jll = "7243133f-43d8-5620-bbf4-c2c921802cf3"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CommonDataModel = "0.4.0"
DataFrames = "1.3.1"
DiskArrays = "0.4.18"
DocStringExtensions = "0.8.6, 0.9.0"
NetCDF_jll = "=400.701.400, =400.702.400, =400.902.5, =400.902.208, =400.902.209, =400.902.210, =400.902.211, =401.900.300"
OrderedCollections = "1.8.1"
julia = "1.10"
